version: "3.8"

services:
  db:
    image: mariadb:11
    container_name: shopping_cart_localization
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME:-shopping_cart_localization}"
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    image: nguyngc/otp2_week4:latest
    build: .
    container_name: shoppingcart-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: "${DB_NAME:-shopping_cart_localization}"
      DB_USERNAME: "${DB_USERNAME:-root}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DISPLAY: host.docker.internal:0

volumes:
  db_data:
